# yazi.toml
[mgr]
show_hidden = true

[opener]
edit = [
	{ run = 'nvim %*',    block = true, desc = "nvim",           for = "windows" },
]
browser = [
	{ run = 'start %*',   orphan = true, desc = "Open in browser", for = "windows" },
]

[open]
rules = [
	{ mime = "text/html", use = ["browser", "edit"] },
]
