# Gruvbox themed starship prompt
palette = "gruvbox"

add_newline = true
format = """$directory$git_branch$git_status$nodejs$python$rust$golang$docker_context\n$character"""
command_timeout = 100

[palettes.gruvbox]
blue = "#83a598"
yellow = "#fabd2f"
orange = "#fe8019"
purple = "#d3869b"
red = "#fb4934"
green = "#b8bb26"
aqua = "#8ec07c"
fg = "#ebdbb2"
bg = "#1d2021"
alt_fg = "#a89984"
alt_bg = "#32302f"

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](orange)"

[directory]
style = "bold blue"
truncation_length = 3
truncate_to_repo = false

[git_branch]
symbol = " "
style = "purple"
format = "[$symbol$branch]($style)"

[git_status]
style = "yellow"
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
deleted = ""
renamed = ""
modified = ""
staged = ""
untracked = ""

[nodejs]
symbol = " "
style = "green"
format = "[$symbol($version)]($style)"

[python]
symbol = " "
style = "yellow"
format = "[$symbol$pyversion]($style)"

[rust]
symbol = " "
style = "orange"
format = "[$symbol($version)]($style)"

[golang]
symbol = " "
style = "aqua"
format = "[$symbol($version)]($style)"

[docker_context]
symbol = " "
style = "blue"
format = "[$symbol$context]($style)"